spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.1.16:1521:orcl
    username: NewCTBT
    password: newctbt
    driver-class-name: oracle.jdbc.driver.OracleDriver
#  redis:
#    host: 127.0.0.1
#    timeout: 1000ms
#    jedis:
#      pool:
#        max-active: 8
#        max-idle: 8
#        max-wait: -1ms
#        min-idle: 0
#    driver-class-name: oracle.jdbc.OracleDriver

server:
  port: 8081
