spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.1.16:1521:orcl
    username: NewCTBT
    password: newctbt
    driver-class-name: oracle.jdbc.driver.OracleDriver
#    driver-class-name: oracle.jdbc.OracleDriver

server:
  port: 8081
